# Generated by Django 4.2.2 on 2023-09-24 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice_analysis_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docketpdf',
            name='truckNo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transferkmscost',
            name='deliveryDate',
            field=models.DateField(default=datetime.datetime(2023, 9, 24, 8, 39, 7, 684091, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transferkmscost',
            name='paidKMS',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='waitingtimecost',
            name='deliveryDate',
            field=models.DateField(default=datetime.datetime(2023, 9, 24, 8, 39, 7, 683003, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='waitingtimecost',
            name='paidKMS',
            field=models.FloatField(default=0),
        ),
    ]
