# Generated by Django 4.2.1 on 2023-09-30 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice_analysis_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferkmscost',
            name='deliveryDate',
            field=models.DateField(default=datetime.datetime(2023, 9, 30, 10, 42, 29, 403728, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='waitingtimecost',
            name='deliveryDate',
            field=models.DateField(default=datetime.datetime(2023, 9, 30, 10, 42, 29, 402727, tzinfo=datetime.timezone.utc)),
        ),
    ]
