# Generated by Django 4.2.1 on 2023-10-02 04:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Basic_app', '0002_alter_clienttruckconnection_startdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docketNumber', models.IntegerField()),
                ('truckNo', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WaitingTimeCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryDate', models.DateField(default=datetime.datetime(2023, 10, 2, 4, 7, 48, 532247, tzinfo=datetime.timezone.utc))),
                ('basePlant', models.CharField(max_length=255)),
                ('paidKMS', models.FloatField(default=0)),
                ('invoiceQuantity', models.FloatField(default=0)),
                ('unit', models.CharField(max_length=255)),
                ('unitPrice', models.FloatField(default=0)),
                ('TotalExGST', models.FloatField(default=0)),
                ('GSTPayable', models.FloatField(default=0)),
                ('TotalInGST', models.FloatField(default=0)),
                ('docketNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trips_details_app.clienttrip')),
            ],
        ),
        migrations.CreateModel(
            name='transferKMSCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryDate', models.DateField(default=datetime.datetime(2023, 10, 2, 4, 7, 48, 533245, tzinfo=datetime.timezone.utc))),
                ('basePlant', models.CharField(max_length=255)),
                ('paidKMS', models.FloatField(default=0)),
                ('invoiceQuantity', models.FloatField(default=0)),
                ('unit', models.CharField(max_length=255)),
                ('unitPrice', models.FloatField(default=0)),
                ('TotalExGST', models.FloatField(default=0)),
                ('GSTPayable', models.FloatField(default=0)),
                ('TotalInGST', models.FloatField(default=0)),
                ('docketNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trips_details_app.clienttrip')),
            ],
        ),
        migrations.CreateModel(
            name='DriverTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('clientName', models.CharField(max_length=200)),
                ('shiftType', models.CharField(max_length=200)),
                ('numberOfLoads', models.IntegerField()),
                ('truckNo', models.IntegerField()),
                ('shiftDate', models.DateTimeField()),
                ('startTime', models.CharField(max_length=200)),
                ('endTime', models.CharField(max_length=200)),
                ('logSheet', models.FileField(upload_to='static/img/finalLogSheet')),
                ('comment', models.CharField(max_length=200)),
                ('basePlant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Basic_app.baseplant')),
                ('driverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basic_app.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Docket',
            fields=[
                ('docketId', models.AutoField(primary_key=True, serialize=False)),
                ('docketNumber', models.IntegerField()),
                ('docketFile', models.FileField(upload_to='static/img/docketFiles')),
                ('waitingTimeInMinutes', models.CharField(max_length=255)),
                ('waitingTimeCost', models.FloatField(default=0)),
                ('transferKMS', models.PositiveIntegerField(default=0)),
                ('transferKMSCost', models.FloatField(default=0)),
                ('cubicMl', models.PositiveIntegerField(default=0)),
                ('cubicMlCost', models.FloatField(default=0)),
                ('minLoad', models.PositiveIntegerField(default=0)),
                ('minLoadCost', models.FloatField(default=0)),
                ('others', models.PositiveIntegerField(default=0)),
                ('othersCost', models.FloatField(default=0)),
                ('tripId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trips_details_app.drivertrip')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled', models.BooleanField(default=False)),
                ('Title', models.CharField(max_length=255)),
                ('Start_Date_Time', models.DateTimeField(default=datetime.datetime(2023, 10, 2, 4, 7, 48, 532247, tzinfo=datetime.timezone.utc))),
                ('End_Date_Time', models.DateTimeField(default=datetime.datetime(2023, 10, 2, 4, 7, 48, 532247, tzinfo=datetime.timezone.utc))),
                ('report_to_origin', models.DateTimeField(default=datetime.datetime(2023, 10, 2, 4, 7, 48, 532247, tzinfo=datetime.timezone.utc))),
                ('Status', models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('dispacted', 'Dispatched'), ('in_progress', 'In Progress'), ('incomplete', 'Incomplete'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='incomplete', max_length=20)),
                ('Origin', models.CharField(max_length=255)),
                ('Recurring', models.CharField(max_length=255)),
                ('Staff_Notes', models.CharField(max_length=1024)),
                ('Created_by', models.CharField(max_length=255)),
                ('Created_time', models.TimeField(auto_now=True)),
                ('Report_Time', models.TimeField()),
                ('Dwell_Time', models.TimeField()),
                ('Block_Time', models.TimeField()),
                ('Total_Time', models.TimeField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basic_app.driver')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basic_app.client')),
            ],
        ),
    ]
