# Generated by Django 4.2.1 on 2023-09-30 10:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_app', '0004_alter_clienttruckconnection_startdate_and_more'),
        ('Trips_details_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docketNumber', models.IntegerField()),
                ('truckNo', models.FloatField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Trip',
            new_name='DriverTrip',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='End_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 30, 10, 42, 29, 427614, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Start_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 30, 10, 42, 29, 427614, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='report_to_origin',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 30, 10, 42, 29, 427614, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='docket',
            name='waitingTime',
            field=models.TimeField(default=datetime.datetime(2023, 9, 30, 10, 42, 29, 426663, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='WaitingTimeCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryDate', models.DateField(default=datetime.datetime(2023, 9, 30, 10, 42, 29, 429668, tzinfo=datetime.timezone.utc))),
                ('basePlant', models.CharField(max_length=255)),
                ('paidKMS', models.FloatField(default=0)),
                ('invoiceQuantity', models.FloatField(default=0)),
                ('unit', models.CharField(max_length=255)),
                ('unitPrice', models.FloatField(default=0)),
                ('TotalExGST', models.FloatField(default=0)),
                ('GSTPayable', models.FloatField(default=0)),
                ('TotalInGST', models.FloatField(default=0)),
                ('docketNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trips_details_app.clienttrip')),
            ],
        ),
        migrations.CreateModel(
            name='transferKMSCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryDate', models.DateField(default=datetime.datetime(2023, 9, 30, 10, 42, 29, 430662, tzinfo=datetime.timezone.utc))),
                ('basePlant', models.CharField(max_length=255)),
                ('paidKMS', models.FloatField(default=0)),
                ('invoiceQuantity', models.FloatField(default=0)),
                ('unit', models.CharField(max_length=255)),
                ('unitPrice', models.FloatField(default=0)),
                ('TotalExGST', models.FloatField(default=0)),
                ('GSTPayable', models.FloatField(default=0)),
                ('TotalInGST', models.FloatField(default=0)),
                ('docketNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trips_details_app.clienttrip')),
            ],
        ),
    ]
