# Generated by Django 4.2.1 on 2023-09-30 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips_details_app', '0002_clienttrip_rename_trip_drivertrip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='End_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 30, 10, 46, 20, 642880, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Start_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 30, 10, 46, 20, 642880, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='report_to_origin',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 30, 10, 46, 20, 642880, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='docket',
            name='waitingTime',
            field=models.TimeField(default=datetime.datetime(2023, 9, 30, 10, 46, 20, 642880, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transferkmscost',
            name='deliveryDate',
            field=models.DateField(default=datetime.datetime(2023, 9, 30, 10, 46, 20, 645873, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='waitingtimecost',
            name='deliveryDate',
            field=models.DateField(default=datetime.datetime(2023, 9, 30, 10, 46, 20, 644876, tzinfo=datetime.timezone.utc)),
        ),
    ]
