# Generated by Django 4.2.1 on 2023-08-19 15:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminTruckNumber', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)])),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driverId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=200)),
                ('truckNo', models.IntegerField()),
                ('shiftType', models.CharField(max_length=200)),
                ('startDateTime', models.DateTimeField()),
                ('endDateTime', models.DateTimeField()),
                ('numberOfLoad', models.IntegerField()),
                ('loadSheet', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
                ('driverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DriverSchedule_app.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Docket',
            fields=[
                ('docketId', models.AutoField(primary_key=True, serialize=False)),
                ('docketNumber', models.IntegerField()),
                ('docketFile', models.CharField(max_length=200)),
                ('tripId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DriverSchedule_app.trip')),
            ],
        ),
        migrations.CreateModel(
            name='ClientTruckConnection',
            fields=[
                ('clientTruckId', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)])),
                ('clientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DriverSchedule_app.client')),
                ('truckNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DriverSchedule_app.admintruck')),
            ],
        ),
    ]
