# Generated by Django 4.2.1 on 2023-09-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DriverSchedule_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='numberOfLog',
            new_name='numberOfLoads',
        ),
    ]
