# Generated by Django 4.2.2 on 2023-09-16 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriverSchedule_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2023, 9, 16, 11, 34, 34, 86202, tzinfo=datetime.timezone.utc)),
        ),
    ]
