# Generated by Django 4.2.2 on 2023-09-15 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriverSchedule_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2023, 9, 15, 12, 43, 14, 773454, tzinfo=datetime.timezone.utc)),
        ),
    ]
