# Generated by Django 4.2.1 on 2023-09-30 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriverSchedule_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2023, 9, 30, 5, 50, 50, 367913, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cost',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2023, 9, 30, 5, 50, 50, 374944, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='docket',
            name='waitingTime',
            field=models.TimeField(default=datetime.datetime(2023, 9, 30, 5, 50, 50, 372934, tzinfo=datetime.timezone.utc)),
        ),
    ]
