# Generated by Django 4.2.2 on 2023-09-23 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriverSchedule_app', '0002_alter_clienttruckconnection_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='docket',
            name='cubicMl',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docket',
            name='cubicMlCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='docket',
            name='minLoad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docket',
            name='minLoadCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='docket',
            name='others',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docket',
            name='othersCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='docket',
            name='transferKMS',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docket',
            name='transferKMSCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='docket',
            name='waitingTime',
            field=models.TimeField(default=datetime.datetime(2023, 9, 23, 4, 36, 16, 72047, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='docket',
            name='waitingTimeCost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2023, 9, 23, 4, 36, 16, 70049, tzinfo=datetime.timezone.utc)),
        ),
    ]
