# Generated by Django 4.2.1 on 2023-09-09 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriverSchedule_app', '0002_rename_numberoflog_trip_numberofloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.date(2023, 9, 9)),
        ),
    ]
