# Generated by Django 4.2.2 on 2023-09-23 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriverSchedule_app', '0004_alter_clienttruckconnection_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2023, 9, 23, 4, 55, 17, 866625, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='docket',
            name='waitingTime',
            field=models.TimeField(default=datetime.datetime(2023, 9, 23, 4, 55, 17, 867827, tzinfo=datetime.timezone.utc)),
        ),
    ]
