# Generated by Django 4.2.2 on 2023-09-13 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriverSchedule_app', '0005_alter_leaverequest_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.date(2023, 9, 13)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='logSheet',
            field=models.FileField(upload_to='Temp_Load_Sheet/'),
        ),
    ]
