# Generated by Django 4.2.2 on 2023-09-14 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriverSchedule_app', '0006_alter_clienttruckconnection_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.date(2023, 9, 14)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='logSheet',
            field=models.FileField(upload_to='DriverSchedule_app/tempLoadSheet/'),
        ),
    ]
