# Generated by Django 4.2.2 on 2023-09-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriverSchedule_app', '0007_alter_clienttruckconnection_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='logSheet',
            field=models.FileField(upload_to='static/img/finalLogSheet'),
        ),
    ]
