# Generated by Django 4.2.2 on 2023-09-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriverSchedule_app', '0008_alter_trip_logsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='docketFile',
            field=models.FileField(upload_to='static/img/docketFiles'),
        ),
    ]
