# Generated by Django 4.2.1 on 2023-10-02 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2023, 10, 2, 4, 7, 48, 527261, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cost',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2023, 10, 2, 4, 7, 48, 527261, tzinfo=datetime.timezone.utc)),
        ),
    ]
