# Generated by Django 4.2.1 on 2023-09-30 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2023, 9, 30, 9, 57, 25, 563064, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cost',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2023, 9, 30, 9, 57, 25, 564031, tzinfo=datetime.timezone.utc)),
        ),
    ]
