# Generated by Django 4.2.1 on 2023-10-02 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_app', '0002_alter_clienttruckconnection_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2023, 10, 2, 4, 8, 4, 626353, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cost',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2023, 10, 2, 4, 8, 4, 627400, tzinfo=datetime.timezone.utc)),
        ),
    ]
