# Generated by Django 4.2.1 on 2023-09-30 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_app', '0003_alter_clienttruckconnection_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2023, 9, 30, 10, 42, 29, 414648, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cost',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2023, 9, 30, 10, 42, 29, 416643, tzinfo=datetime.timezone.utc)),
        ),
    ]
