# Generated by Django 4.2.2 on 2023-09-16 11:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DriverSchedule_app', '0002_alter_clienttruckconnection_startdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled', models.BooleanField(default=False)),
                ('Title', models.CharField(max_length=255)),
                ('Start_Date_Time', models.DateTimeField(default=datetime.datetime(2023, 9, 16, 11, 34, 34, 89048, tzinfo=datetime.timezone.utc))),
                ('End_Date_Time', models.DateTimeField(default=datetime.datetime(2023, 9, 16, 11, 34, 34, 89048, tzinfo=datetime.timezone.utc))),
                ('report_to_origin', models.DateTimeField(default=datetime.datetime(2023, 9, 16, 11, 34, 34, 89048, tzinfo=datetime.timezone.utc))),
                ('Status', models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('dispacted', 'Dispatched'), ('in_progress', 'In Progress'), ('incomplete', 'Incomplete'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='incomplete', max_length=20)),
                ('Origin', models.CharField(max_length=255)),
                ('Recurring', models.CharField(max_length=255)),
                ('Staff_Notes', models.CharField(max_length=1024)),
                ('Created_by', models.CharField(max_length=255)),
                ('Created_time', models.TimeField(auto_now=True)),
                ('Report_Time', models.TimeField()),
                ('Dwell_Time', models.TimeField()),
                ('Block_Time', models.TimeField()),
                ('Total_Time', models.TimeField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DriverSchedule_app.driver')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DriverSchedule_app.client')),
            ],
        ),
    ]
