# Generated by Django 4.2.1 on 2023-09-09 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_trip', '0002_appointment_delete_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='End_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 12, 54, 44, 206141, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Start_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 12, 54, 44, 206141, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='report_to_origin',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 12, 54, 44, 206141, tzinfo=datetime.timezone.utc)),
        ),
    ]
